name: MinigamePlugin
version: '1.0-SNAPSHOT'
main: me.stavgordeev.plugin.MinigamePlugin
api-version: '1.21'
commands:
  nuke:
    description: Nukes the surrounding area. Needs to specify the radius of the nuke.
    usage: /<command> <radius>
  minigame:
    description: Shows the minigame menu
    usage: /<command> <name>
  mg_disco_mayhem:
    description: Starts the Disco Mayhem minigame
    usage: /<command> <state>
  mg_blueprint_bazaar:
    description: Starts the Blueprint Bazaar minigame
    usage: /<command> <state>




  push_block:
    description: Pushes the block in a specified coordinate by a specified amount of blocks in a specified direction. The block will be pushed every specified interval by 1 block in ticks.
    usage: /<command> <x> <y> <z> <amount> <direction> <interval>
  give_diamonds:
    description: Gives the player 3 diamonds
    usage: /<command>